backend:
  name: git-gateway
  branch: master

media_folder: 'src/structures/images'
public_folder: '/src/structures/images'

locale: 'en'
display_url: 'https://www.polycanyon.com'

collections:
  - name: 'structures'
    label: 'Structures'
    delete: false
    create: false
    files:
      - label: 'All Structures'
        name: 'all_structures'
        file: 'public/data/structuresInfo.json'
        fields:
          - name: 'structures'
            label: 'Structures'
            widget: 'list'
            summary: '{{fields.names.0}} (#{{fields.number}})'
            minimize_collapsed: true
            label_singular: 'Structure'
            allow_add: false
            allow_delete: false
            collapsed: false
            fields:
              - { label: 'ID', name: '_id', widget: 'hidden', required: true }
              - {
                  label: 'Number',
                  name: 'number',
                  widget: 'hidden',
                  required: true,
                }
              - { label: 'URL', name: 'url', widget: 'hidden', required: true }
              - label: 'Names'
                name: 'names'
                widget: 'list'
                field: { label: 'Name', name: '', widget: 'string' }
                hint: 'First name will be used as primary title'
                required: true
              - {
                  label: 'Year',
                  name: 'year',
                  widget: 'string',
                  required: true,
                }
              - {
                  label: 'Department',
                  name: 'department',
                  widget: 'list',
                  default: [],
                  required: false,
                }
              - label: 'Advisor/Builders'
                name: 'advisor_builders'
                widget: 'list'
                required: true
                fields:
                  - {
                      label: 'Name',
                      name: 'name',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      label: 'Role',
                      name: 'role',
                      widget: 'list',
                      required: true,
                    }
              - {
                  label: 'Description',
                  name: 'description',
                  widget: 'text',
                  required: true,
                }
              - {
                  label: 'Extended Description',
                  name: 'extended_description',
                  widget: 'text',
                  required: true,
                }
              - label: 'Status'
                name: 'status'
                widget: 'select'
                options:
                  - { label: 'Active', value: 'Active' }
                  - { label: 'Ghost', value: 'Ghost' }
                  - { label: 'Planned', value: 'Planned' }
                required: true
              - {
                  label: 'Style',
                  name: 'style',
                  widget: 'string',
                  default: '',
                  required: false,
                }
              - {
                  label: 'Tags',
                  name: 'tags',
                  widget: 'list',
                  default: [],
                  required: false,
                }
              - label: 'Location'
                name: 'location'
                widget: 'object'
                required: true
                fields:
                  - {
                      label: 'Latitude',
                      name: 'latitude',
                      widget: 'hidden',
                      required: true,
                    }
                  - {
                      label: 'Longitude',
                      name: 'longitude',
                      widget: 'hidden',
                      required: true,
                    }
              - label: 'Images'
                name: 'images'
                widget: 'list'
                required: true
                fields:
                  - {
                      label: 'Type',
                      name: 'type',
                      widget: 'select',
                      options: ['main', 'closeup', 'historical', 'other'],
                      required: true,
                    }
                  - {
                      label: 'Orientation',
                      name: 'orientation',
                      widget: 'hidden',
                      required: true,
                    }
                  - {
                      label: 'Path',
                      name: 'path',
                      widget: 'hidden',
                      required: true,
                    }
                  - {
                      label: 'Description',
                      name: 'description',
                      widget: 'string',
                      required: true,
                    }
              - label: 'Links'
                name: 'links'
                widget: 'list'
                required: false
                fields:
                  - {
                      label: 'Link Type',
                      name: 'linkType',
                      widget: 'hidden',
                      required: true,
                    }
                  - {
                      label: 'URL',
                      name: 'URL',
                      widget: 'hidden',
                      required: true,
                    }
                  - {
                      label: 'Title',
                      name: 'title',
                      widget: 'string',
                      required: true,
                    }
